In [1]:
import pandas as pd
from pathlib import Path

In [2]:
DATA_DIR = Path("../data/steam")
PREPRO_WORK_DIR = DATA_DIR / "preprocessed"

In [3]:
users_df = pd.read_pickle(PREPRO_WORK_DIR / "users_df.pkl")
users_df

,user_id,items_count,steam_id,user_url,items,reviews
0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"[{'item_id': '10', 'item_name': 'Counter-Strik...","[{'funny': '', 'helpful': 'No ratings yet', 'i..."
1,js41637,888,76561198035864385,http://steamcommunity.com/id/js41637,"[{'item_id': '10', 'item_name': 'Counter-Strik...","[{'funny': '', 'helpful': '15 of 20 people (75..."
2,evcentric,137,76561198007712555,http://steamcommunity.com/id/evcentric,"[{'item_id': '1200', 'item_name': 'Red Orchest...","[{'funny': '', 'helpful': 'No ratings yet', 'i..."
3,doctr,541,76561198002099482,http://steamcommunity.com/id/doctr,"[{'item_id': '300', 'item_name': 'Day of Defea...","[{'funny': '', 'helpful': '2 of 2 people (100%..."
4,maplemage,629,76561198026584251,http://steamcommunity.com/id/maplemage,"[{'item_id': '240', 'item_name': 'Counter-Stri...","[{'funny': '3 people found this review funny',..."
...,...,...,...,...,...,...
26430,76561198306599751,7,76561198306599751,http://steamcommunity.com/profiles/76561198306...,"[{'item_id': '4000', 'item_name': 'Garry's Mod...","[{'funny': '', 'helpful': '0 of 1 people (0%) ..."
26431,Ghoustik,4,76561198308105615,http://steamcommunity.com/id/Ghoustik,"[{'item_id': '302830', 'item_name': 'BLOCKADE ...","[{'funny': '', 'helpful': '0 of 1 people (0%) ..."
26432,76561198310819422,12,76561198310819422,http://steamcommunity.com/profiles/76561198310...,"[{'item_id': '268420', 'item_name': 'Aura King...","[{'funny': '1 person found this review funny',..."
26433,76561198312638244,36,76561198312638244,http://steamcommunity.com/profiles/76561198312...,"[{'item_id': '10', 'item_name': 'Counter-Strik...","[{'funny': '', 'helpful': 'No ratings yet', 'i..."
26434,LydiaMorley,0,76561198313816521,http://steamcommunity.com/id/LydiaMorley,[],"[{'funny': '1 person found this review funny',..."

In [4]:
users_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 26435 entries, 0 to 26434
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   user_id      26435 non-null  object
 1   items_count  26435 non-null  int64
 2   steam_id     26435 non-null  object
 3   user_url     26435 non-null  object
 4   items        26435 non-null  object
 5   reviews      26435 non-null  object
dtypes: int64(1), object(5)
memory usage: 1.4+ MB

In [5]:
# drop_duplicates work around for list/array columns
users_df = users_df[~users_df.astype({"items": str, "reviews": str}).duplicated()]
users_df.shape

(25495, 6)

In [6]:
users_df['reviews'][0]

array([{'funny': '', 'helpful': 'No ratings yet', 'item_id': '1250', 'last_edited': '', 'posted': 'Posted November 5, 2011.', 'recommend': True, 'review': 'Simple yet with great replayability. In my opinion does "zombie" hordes and team work better than left 4 dead plus has a global leveling system. Alot of down to earth "zombie" splattering fun for the whole family. Amazed this sort of FPS is so rare.'},
       {'funny': '', 'helpful': 'No ratings yet', 'item_id': '22200', 'last_edited': '', 'posted': 'Posted July 15, 2011.', 'recommend': True, 'review': "It's unique and worth a playthrough."},
       {'funny': '', 'helpful': 'No ratings yet', 'item_id': '43110', 'last_edited': '', 'posted': 'Posted April 21, 2011.', 'recommend': True, 'review': 'Great atmosphere. The gunplay can be a bit chunky at times but at the end of the day this game is definitely worth it and I hope they do a sequel...so buy the game so I get a sequel!'}],
      dtype=object)

In [7]:
def filter_users(df: pd.DataFrame):
    new_df = df.copy()
    new_df = new_df[new_df['reviews'].apply(lambda x : len(x) >=5)]
    new_df = new_df[new_df['items_count'] > 0]
    return new_df

users_df = filter_users(users_df).reset_index(drop=True)
users_df

,user_id,items_count,steam_id,user_url,items,reviews
0,evcentric,137,76561198007712555,http://steamcommunity.com/id/evcentric,"[{'item_id': '1200', 'item_name': 'Red Orchest...","[{'funny': '', 'helpful': 'No ratings yet', 'i..."
1,doctr,541,76561198002099482,http://steamcommunity.com/id/doctr,"[{'item_id': '300', 'item_name': 'Day of Defea...","[{'funny': '', 'helpful': '2 of 2 people (100%..."
2,DJKamBer,152,76561198026039330,http://steamcommunity.com/id/DJKamBer,"[{'item_id': '4000', 'item_name': 'Garry's Mod...","[{'funny': '', 'helpful': '2 of 4 people (50%)..."
3,76561198070565427,75,76561198070565427,http://steamcommunity.com/profiles/76561198070...,"[{'item_id': '4000', 'item_name': 'Garry's Mod...","[{'funny': '', 'helpful': 'No ratings yet', 'i..."
4,diego9031,200,76561198082027703,http://steamcommunity.com/id/diego9031,"[{'item_id': '4000', 'item_name': 'Garry's Mod...","[{'funny': '', 'helpful': '0 of 1 people (0%) ..."
...,...,...,...,...,...,...
2956,TripleQMark,66,76561198202638474,http://steamcommunity.com/id/TripleQMark,"[{'item_id': '240', 'item_name': 'Counter-Stri...","[{'funny': '', 'helpful': '3 of 3 people (100%..."
2957,76561198208704549,45,76561198208704549,http://steamcommunity.com/profiles/76561198208...,"[{'item_id': '109600', 'item_name': 'Neverwint...","[{'funny': '1 person found this review funny',..."
2958,bestcustomurlevermade,21,76561198208817785,http://steamcommunity.com/id/bestcustomurlever...,"[{'item_id': '4000', 'item_name': 'Garry's Mod...","[{'funny': '', 'helpful': '7 of 11 people (64%..."
2959,76561198236893796,17,76561198236893796,http://steamcommunity.com/profiles/76561198236...,"[{'item_id': '99900', 'item_name': 'Spiral Kni...","[{'funny': '', 'helpful': '4 of 6 people (67%)..."
2960,kimjongadam,57,76561198255497369,http://steamcommunity.com/id/kimjongadam,"[{'item_id': '4000', 'item_name': 'Garry's Mod...","[{'funny': '', 'helpful': '1 of 1 people (100%..."

In [8]:
users_df['items'][0][:5]

array([{'item_id': '1200', 'item_name': 'Red Orchestra: Ostfront 41-45', 'playtime_2weeks': 0, 'playtime_forever': 923},
       {'item_id': '1230', 'item_name': 'Mare Nostrum', 'playtime_2weeks': 0, 'playtime_forever': 0},
       {'item_id': '1280', 'item_name': "Darkest Hour: Europe '44-'45", 'playtime_2weeks': 0, 'playtime_forever': 0},
       {'item_id': '1520', 'item_name': 'DEFCON', 'playtime_2weeks': 0, 'playtime_forever': 158},
       {'item_id': '220', 'item_name': 'Half-Life 2', 'playtime_2weeks': 0, 'playtime_forever': 1323}],
      dtype=object)

In [9]:
users_df['steam_id'].nunique()

2957

In [10]:
owned_games_df = users_df.explode("items", ignore_index=True)
owned_games_df

,user_id,items_count,steam_id,user_url,items,reviews
0,evcentric,137,76561198007712555,http://steamcommunity.com/id/evcentric,"{'item_id': '1200', 'item_name': 'Red Orchestr...","[{'funny': '', 'helpful': 'No ratings yet', 'i..."
1,evcentric,137,76561198007712555,http://steamcommunity.com/id/evcentric,"{'item_id': '1230', 'item_name': 'Mare Nostrum...","[{'funny': '', 'helpful': 'No ratings yet', 'i..."
2,evcentric,137,76561198007712555,http://steamcommunity.com/id/evcentric,"{'item_id': '1280', 'item_name': 'Darkest Hour...","[{'funny': '', 'helpful': 'No ratings yet', 'i..."
3,evcentric,137,76561198007712555,http://steamcommunity.com/id/evcentric,"{'item_id': '1520', 'item_name': 'DEFCON', 'pl...","[{'funny': '', 'helpful': 'No ratings yet', 'i..."
4,evcentric,137,76561198007712555,http://steamcommunity.com/id/evcentric,"{'item_id': '220', 'item_name': 'Half-Life 2',...","[{'funny': '', 'helpful': 'No ratings yet', 'i..."
...,...,...,...,...,...,...
546967,kimjongadam,57,76561198255497369,http://steamcommunity.com/id/kimjongadam,"{'item_id': '236110', 'item_name': 'Dungeon De...","[{'funny': '', 'helpful': '1 of 1 people (100%..."
546968,kimjongadam,57,76561198255497369,http://steamcommunity.com/id/kimjongadam,"{'item_id': '417860', 'item_name': 'Emily is A...","[{'funny': '', 'helpful': '1 of 1 people (100%..."
546969,kimjongadam,57,76561198255497369,http://steamcommunity.com/id/kimjongadam,"{'item_id': '427730', 'item_name': 'Who's Your...","[{'funny': '', 'helpful': '1 of 1 people (100%..."
546970,kimjongadam,57,76561198255497369,http://steamcommunity.com/id/kimjongadam,"{'item_id': '449540', 'item_name': 'There's Po...","[{'funny': '', 'helpful': '1 of 1 people (100%..."
546971,kimjongadam,57,76561198255497369,http://steamcommunity.com/id/kimjongadam,"{'item_id': '466910', 'item_name': 'Worm.is: T...","[{'funny': '', 'helpful': '1 of 1 people (100%..."

In [11]:
owned_games_df["items"][0]

{'item_id': '1200',
 'item_name': 'Red Orchestra: Ostfront 41-45',
 'playtime_2weeks': 0,
 'playtime_forever': 923}

In [12]:
games_temp_df = pd.DataFrame.from_records(owned_games_df["items"])
games_temp_df

,item_id,item_name,playtime_2weeks,playtime_forever
0,1200,Red Orchestra: Ostfront 41-45,0,923
1,1230,Mare Nostrum,0,0
2,1280,Darkest Hour: Europe '44-'45,0,0
3,1520,DEFCON,0,158
4,220,Half-Life 2,0,1323
...,...,...,...,...
546967,236110,Dungeon Defenders II,0,6
546968,417860,Emily is Away,0,76
546969,427730,Who's Your Daddy,0,21
546970,449540,There's Poop In My Soup,0,33
546971,466910,Worm.is: The Game,0,0

In [13]:
pivot_temp_df = pd.concat([owned_games_df, games_temp_df], axis=1)
pivot_temp_df

,user_id,items_count,steam_id,user_url,items,reviews,item_id,item_name,playtime_2weeks,playtime_forever
0,evcentric,137,76561198007712555,http://steamcommunity.com/id/evcentric,"{'item_id': '1200', 'item_name': 'Red Orchestr...","[{'funny': '', 'helpful': 'No ratings yet', 'i...",1200,Red Orchestra: Ostfront 41-45,0,923
1,evcentric,137,76561198007712555,http://steamcommunity.com/id/evcentric,"{'item_id': '1230', 'item_name': 'Mare Nostrum...","[{'funny': '', 'helpful': 'No ratings yet', 'i...",1230,Mare Nostrum,0,0
2,evcentric,137,76561198007712555,http://steamcommunity.com/id/evcentric,"{'item_id': '1280', 'item_name': 'Darkest Hour...","[{'funny': '', 'helpful': 'No ratings yet', 'i...",1280,Darkest Hour: Europe '44-'45,0,0
3,evcentric,137,76561198007712555,http://steamcommunity.com/id/evcentric,"{'item_id': '1520', 'item_name': 'DEFCON', 'pl...","[{'funny': '', 'helpful': 'No ratings yet', 'i...",1520,DEFCON,0,158
4,evcentric,137,76561198007712555,http://steamcommunity.com/id/evcentric,"{'item_id': '220', 'item_name': 'Half-Life 2',...","[{'funny': '', 'helpful': 'No ratings yet', 'i...",220,Half-Life 2,0,1323
...,...,...,...,...,...,...,...,...,...,...
546967,kimjongadam,57,76561198255497369,http://steamcommunity.com/id/kimjongadam,"{'item_id': '236110', 'item_name': 'Dungeon De...","[{'funny': '', 'helpful': '1 of 1 people (100%...",236110,Dungeon Defenders II,0,6
546968,kimjongadam,57,76561198255497369,http://steamcommunity.com/id/kimjongadam,"{'item_id': '417860', 'item_name': 'Emily is A...","[{'funny': '', 'helpful': '1 of 1 people (100%...",417860,Emily is Away,0,76
546969,kimjongadam,57,76561198255497369,http://steamcommunity.com/id/kimjongadam,"{'item_id': '427730', 'item_name': 'Who's Your...","[{'funny': '', 'helpful': '1 of 1 people (100%...",427730,Who's Your Daddy,0,21
546970,kimjongadam,57,76561198255497369,http://steamcommunity.com/id/kimjongadam,"{'item_id': '449540', 'item_name': 'There's Po...","[{'funny': '', 'helpful': '1 of 1 people (100%...",449540,There's Poop In My Soup,0,33
546971,kimjongadam,57,76561198255497369,http://steamcommunity.com/id/kimjongadam,"{'item_id': '466910', 'item_name': 'Worm.is: T...","[{'funny': '', 'helpful': '1 of 1 people (100%...",466910,Worm.is: The Game,0,0

# Recommend score?

In [14]:
pivot_temp_df["recommend_score"] = pivot_temp_df["playtime_forever"] + 3 * pivot_temp_df["playtime_2weeks"] + 100 * pivot_temp_df["items_count"]

In [15]:
pivot_users_df = pd.pivot_table(pivot_temp_df, index="steam_id", columns="item_id", values="recommend_score")
pivot_users_df = pivot_users_df.fillna(-1)
pivot_users_df

item_id,10,100,10000,1002,100400,100410,10080,10090,100970,10100,...,9970,99700,9980,99810,99830,99890,9990,99900,99910,99920
steam_id,,,,,,,,,,,,,,,,,,,,,
76561197960304530,165023.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,161700.0,...,-1.0,161700.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
76561197960493731,40514.0,-1.0,40500.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,40523.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
76561197960540939,110300.0,110300.0,110300.0,-1.0,-1.0,-1.0,-1.0,110300.0,-1.0,110300.0,...,-1.0,110300.0,-1.0,110300.0,110300.0,-1.0,-1.0,-1.0,-1.0,-1.0
76561197960889906,59036.0,59000.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,59019.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
76561197961040696,41206.0,41200.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76561198280059944,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
76561198295803313,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,1101.0,-1.0,-1.0
76561198297906261,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
76561198299095634,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
76561198308665434,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0

In [16]:
# assert that `steam_id` and `item_id` are unique
assert pivot_users_df.index.nunique() == pivot_users_df.shape[0]
assert pivot_users_df.keys().nunique() == pivot_users_df.shape[1]

In [17]:
pivot_users_df.to_pickle(PREPRO_WORK_DIR / "pivot_users_games_recscore_df.pkl")

In [18]:
matrix = pivot_users_df.to_numpy()
matrix

array([[ 1.65023e+05, -1.00000e+00, -1.00000e+00, ..., -1.00000e+00,
        -1.00000e+00, -1.00000e+00],
       [ 4.05140e+04, -1.00000e+00,  4.05000e+04, ..., -1.00000e+00,
        -1.00000e+00, -1.00000e+00],
       [ 1.10300e+05,  1.10300e+05,  1.10300e+05, ..., -1.00000e+00,
        -1.00000e+00, -1.00000e+00],
       ...,
       [-1.00000e+00, -1.00000e+00, -1.00000e+00, ..., -1.00000e+00,
        -1.00000e+00, -1.00000e+00],
       [-1.00000e+00, -1.00000e+00, -1.00000e+00, ..., -1.00000e+00,
        -1.00000e+00, -1.00000e+00],
       [-1.00000e+00, -1.00000e+00, -1.00000e+00, ..., -1.00000e+00,
        -1.00000e+00, -1.00000e+00]])